### PR TITLE
added readme

### PR DESCRIPTION
**Pull request by danrot**

### CODE REVIEW

**Comment by wachterjohannes** [comment]
@danrot maybe add also a link to this docs https://github.com/sulu/sulu-docs/tree/develop/bundles/automation

**Comment by danrot** [comment]
@wachterjohannes Shouldn't we wait with that after the release? Then we can link to the real documentation.

**Comment by wachterjohannes** [comment]
@danrot ok thats good. will you create an issue for that?

**Comment by danrot** [comment]
@wachterjohannes Done: https://github.com/sulu/SuluAutomationBundle/issues/3

**Pull request merged**
